CREATE DATABASE IF NOT EXISTS CARSELLER;
use CARSELLER;

CREATE TABLE EMPLEADO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(60) NOT NULL,
    APELLIDO VARCHAR(60) NOT NULL,
    TIPO_DOCUMENTO ENUM('CC', 'CE', 'TE', 'TI'),
    N_DOCUMENTO INT NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    SALARIO_BASE INT NOT NULL,
    ACTIVO BOOLEAN DEFAULT TRUE
);
CREATE TABLE NOMINA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    EMPLEADO_ID INT UNIQUE NOT NULL,
    PERIODO_ANUAL YEAR NOT NULL,
    PERIODO_MES TINYINT NOT NULL CHECK (PERIODO_MES BETWEEN 1 AND 12),
    FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADO(ID)
);

CREATE TABLE CONCEPTO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    FECHA DATE NOT NULL,
    MONTO INT NOT NULL,
    NOMINA_ID INT NOT NULL,
    FOREIGN KEY (NOMINA_ID) REFERENCES NOMINA(ID)
);

CREATE TABLE NOVEDADES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    JUSTIFICACION BOOLEAN DEFAULT FALSE,
    NOMINA_ID INT NOT NULL,
    FOREIGN KEY (NOMINA_ID) REFERENCES NOMINA(ID)
);


CREATE TABLE CARGO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);

ALTER TABLE EMPLEADO
ADD COLUMN CARGO_ID INT NOT NULL;

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_CARGO_CONSTRAINT
FOREIGN KEY (CARGO_ID) REFERENCES CARGO(ID);

CREATE TABLE SUCURSAL(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    DIRECCION VARCHAR(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE AREA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    SUCURSAL_ID INT NOT NULL,
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID)
);

ALTER TABLE EMPLEADO
ADD COLUMN SUCURSAL_ID INT NOT NULL;

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_SUCURSAL_CONSTRAINT
FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSAL(ID);

ALTER TABLE EMPLEADO
ADD COLUMN AREA_ID INT NOT NULL;

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_AREA_CONSTRAINT
FOREIGN KEY (AREA_ID) REFERENCES AREA(ID);
